In [10]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score


from sklearn.datasets import load_iris
iris = load_iris()

In [3]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [7]:
#logistic regrestion

In [45]:
score_L = cross_val_score(LogisticRegression(),iris.data,iris.target,cv=5)
score_L

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [46]:
np.average(score_L)

np.float64(0.9733333333333334)

In [13]:
#svc

In [42]:
score_S = cross_val_score(SVC(),iris.data,iris.target,cv=5)
score_S

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [43]:
np.average(score_S)

np.float64(0.9666666666666666)

In [ ]:
#decision tree classifier

In [19]:
score_D = cross_val_score(DecisionTreeClassifier(),iris.data,iris.target,cv=5)
score_D

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [20]:
np.average(score_D)

np.float64(0.9600000000000002)

In [21]:
#random forest

In [40]:
score_r = cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target,cv=5)
score_r

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [41]:
np.average(score_r)

np.float64(0.9666666666666668)