In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('spam.csv')
df.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
df.shape

(5572, 3)

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [8]:
X_train.shape

(4457,)

In [ ]:
X_test.shape

(1115,)

In [9]:
type(X_train)

pandas.core.series.Series

In [14]:
type(X_train.values)

numpy.ndarray

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7777 sparse matrix of type '<class 'numpy.int64'>'
	with 59996 stored elements in Compressed Sparse Row format>

In [15]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [16]:
X_train_cv.shape


(4457, 7777)

In [20]:
v.get_feature_names_out()[6771:6781]


array(['teachers', 'teaches', 'teaching', 'team', 'teams', 'tear',
       'tears', 'tease', 'teasing', 'tech'], dtype=object)

In [21]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_r

In [22]:
v.vocabulary_

{'haha': 3317,
 'can': 1636,
 'but': 1581,
 'having': 3386,
 'dinner': 2347,
 'with': 7577,
 'my': 4698,
 'cousin': 2055,
 'shopping': 6150,
 'lor': 4244,
 'them': 6864,
 'raining': 5587,
 'mah': 4352,
 'hard': 3357,
 'leave': 4100,
 'orchard': 5015,
 'ex': 2704,
 'wife': 7540,
 'was': 7418,
 'not': 4860,
 'able': 767,
 'to': 6968,
 'have': 3380,
 'kids': 3970,
 'do': 2392,
 'you': 7736,
 'want': 7406,
 'one': 4974,
 'day': 2190,
 'evry': 2701,
 'emotion': 2595,
 'dsn': 2490,
 'hav': 3377,
 'words': 7616,
 'wish': 7570,
 'prayrs': 5408,
 'if': 3630,
 'smile': 6293,
 'world': 7624,
 'is': 3781,
 'wit': 7576,
 'othrwise': 5039,
 'even': 2676,
 'drop': 2475,
 'of': 4926,
 'tear': 6776,
 'lik': 4152,
 'stay': 6501,
 'so': 6322,
 'happy': 3356,
 'good': 3199,
 'morning': 4626,
 'keep': 3944,
 'smiling': 6297,
 'well': 7486,
 'for': 2957,
 'class': 1838,
 'babe': 1182,
 'never': 4787,
 'came': 1631,
 'back': 1190,
 'me': 4445,
 'hope': 3517,
 'nice': 4802,
 'sleep': 6260,
 'love': 4265,
 'me

In [23]:
X_train_np = X_train_cv.toarray()
X_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
np.where(X_train_np[0]>0)

(array([1581, 1636, 2055, 2347, 3317, 3386, 4698, 7577]),)

In [25]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [26]:
X_test_cv = v.transform(X_test)

In [27]:
model.score(X_train_cv, y_train)

0.9921471842046219

In [35]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = model.predict(X_test_cv)

In [34]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       973
           1       0.98      0.92      0.95       142

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [31]:
confusion_matrix(y_test, y_pred)

array([[971,   2],
       [ 12, 130]])

In [32]:
accuracy_score(y_test, y_pred)

0.9874439461883409

In [36]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [37]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb_model', MultinomialNB())
])

In [38]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('nb_model', MultinomialNB())])

In [39]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       973
           1       0.98      0.92      0.95       142

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

