In [2]:
import tensorflow_hub as hub
import tensorflow_text as text

In [3]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [4]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [7]:
text_test = ['nice movie indeed', 'not a good movie', 'i like it', 'i love python']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [8]:
text_preprocessed['input_type_ids']

<tf.Tensor: shape=(4, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0

In [9]:
text_preprocessed['input_type_ids']


<tf.Tensor: shape=(4, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0

In [10]:
text_preprocessed['input_word_ids']


<tf.Tensor: shape=(4, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [11]:
bert_model = hub.KerasLayer(encoder_url)

In [12]:
bert_results = bert_model(text_preprocessed)

In [13]:
bert_results.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [14]:
bert_results['sequence_output']


<tf.Tensor: shape=(4, 128, 768), dtype=float32, numpy=
array([[[ 0.07292038,  0.08567819,  0.14476818, ..., -0.09677104,
          0.08722129,  0.07711115],
        [ 0.17839423, -0.19006088,  0.5034945 , ..., -0.05869839,
          0.32717085, -0.1557851 ],
        [ 0.18701482, -0.43388808, -0.4887518 , ..., -0.15502734,
          0.00145212, -0.2447093 ],
        ...,
        [ 0.12083092,  0.12884219,  0.46453527, ...,  0.07375541,
          0.17441949,  0.16522095],
        [ 0.07967934, -0.01190676,  0.5022541 , ...,  0.13777755,
          0.21002199,  0.00624582],
        [-0.0721267 , -0.28303483,  0.5903334 , ...,  0.47551936,
          0.16668457, -0.08920334]],

       [[-0.09083433,  0.03454585,  0.07018345, ..., -0.23317218,
          0.3287341 ,  0.12686096],
        [-0.10079499, -0.48202956, -0.2113955 , ..., -0.46991193,
          0.8993043 ,  0.1833117 ],
        [-0.38712707, -0.6422216 ,  0.07314214, ..., -0.7959594 ,
          0.53556085,  0.52957904],
        ...,

In [15]:
bert_results['pooled_output']


<tf.Tensor: shape=(4, 768), dtype=float32, numpy=
array([[-0.7917742 , -0.21411942,  0.49769473, ...,  0.2446517 ,
        -0.47334495,  0.81758726],
       [-0.81765383, -0.2771378 ,  0.41413888, ...,  0.24631435,
        -0.5010084 ,  0.84768677],
       [-0.9020241 , -0.21037832, -0.19705452, ..., -0.24390136,
        -0.62704384,  0.9186788 ],
       [-0.86115324, -0.23277387,  0.3820111 , ...,  0.4286715 ,
        -0.61306167,  0.86048734]], dtype=float32)>

In [16]:
len(bert_results['encoder_outputs'])


12

In [17]:
bert_results['encoder_outputs']


[<tf.Tensor: shape=(4, 128, 768), dtype=float32, numpy=
 array([[[ 0.12901427,  0.00644747, -0.03614963, ...,  0.0499963 ,
           0.06149199, -0.02657558],
         [ 1.1753383 ,  1.2140789 ,  1.1569979 , ...,  0.11634379,
          -0.35855353, -0.4049018 ],
         [ 0.03859042,  0.5386995 , -0.21089819, ...,  0.21858224,
           0.7260168 , -1.1158607 ],
         ...,
         [-0.07587031, -0.25421903,  0.7075511 , ...,  0.50542027,
          -0.18878669,  0.1502835 ],
         [-0.16066608, -0.2808969 ,  0.5759708 , ...,  0.5275857 ,
          -0.11141355,  0.02887544],
         [-0.04428175, -0.20279607,  0.59093577, ...,  0.8133836 ,
          -0.39075813, -0.02601749]],
 
        [[ 0.20501369,  0.03905918, -0.07497337, ...,  0.09874617,
           0.05935258,  0.05931485],
         [ 0.14603344,  0.35350734,  0.6622684 , ...,  0.66267323,
          -0.34699166, -0.19278206],
         [ 0.4451217 ,  0.4517754 ,  0.03200405, ..., -0.04090012,
           0.4059525 ,  0.28